### ISSUE TITLE
Questions and feedback re: SaaS website

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/saas-website#1]
This is a work-in-progress and there are few things I’m not happy about (choice of images, overall composition, font sizes, copy, consistency, etc). I will improve the design later but want to focus on key technical issues for now and would appreciate some help and feedback if and when you have time:

- FORM (Pricing page): The small screen is fine but what I want to do after that is to have the first box (free trial) on top on its own line and have two boxes below next to each other on mid-size screens, then all four on one line next to each in large screen (`xs-1 s-1-2 m-1-2 l-1-4`) but it doesn’t work for some reason and I cannot figure where the problem is (just put borders around boxes temporarily for convenience).  

- TABLE (Tour page): I thought it would be cool to have a responsive table here with a fixed header column on left side so the user could scroll horizontally. I tried a couple examples I found online but none really worked so I guess I will stick to a simpler solution. One particular issue I had here was to do with columns as `min-width` did not work. Any ideas?  

- Markbot says `font-size`, `font-weight` and `line-height` should not be used in CSS file although we used them in media queries earlier in the course. I know that Typografier classes are expected here and used them for the base size but how can I use them for larger screens or what would be the best way to deal with this issue?  

- Re: social icons in the footer, I gave them a class of `i-32` for base size but what is the best way to adjust the size in larger screens? To use some pseudo code for the HTML tags in media queries and assign them other classes (i-64, i-128)? I think you had a video on this but cannot find it for some reason. 

The above is also a similar issue I’m having with navigation menu and h1 (although these are about responsiveness of fonts and not icons). 

I really don't want to take too much of your time. Just a few words or references to the material would be enough and appreciated.

Thanks a lot!

@thomasjbradley

**Comment by thomasjbradley** [comment]
> FORM (Pricing page):

It’s because of the `width` on `.price-cat`—it’s overwriting the grid widths.

> TABLE (Tour page):

- Fixed table headers are so difficult—it’s not worth your time to figure out.
- Min-width columns are annoying but doable. The trick is to have to `<col>` elements, one with a fixed width & one without. The cell you want to have a min-width then spans both those columns.

```html
<table>
  <colgroup>
    <col style="width: 3em">
    <col>
  </colgroup>
  <col>
  <tbody>
    <tr>
     <td colspan="2">Min-width col</td>
     <td>Flex col</td>
    </tr>
  </tbody>
</table>
```

> Markbot says font-size, font-weight and line-height 

You want to be able to use different font sizes at different screen sizes?

> Re: social icons in the footer, I gave them a class of i-32

There are sizes based on the font size, you can see them on the Typografier cheat sheet:
https://learn-the-web.algonquindesign.ca/topics/typografier-cheat-sheet/#icons

**Comment by C-G-G** [comment]
Thank you @thomasjbradley ! Both FORM (rather "comparison feature") on Pricing page and TABLE on Tour page are in much better shape. 

**TABLE**: I replaced `thead` with `colgroup` but Markbot still requires `thead` and `th[scope]`. Can I use both or should I just ignore Markbot? :)

Re: **fonts**, yes, I want to be able to use different font sizes at different screen sizes so increased `font-size` and `line-height` using media queries as we did in earlier lessons but Markbot doesn't like it (see attached screenshot and my code commented out in main.css). Could this be a glitch?

Re: **social icons**, if these are based on the font size, does that mean that taking care of the previous issue would automatically resolve this issue? If these are not related and I'm supposed to use the classes on the Typografier cheat sheet, how can I apply them to tags for different screen sizes? If through media queries, how can I select the HTML tag, via some pseudo selector? Hope I'm not confusing you.

<img width="774" alt="Screen Shot 2021-09-24 at 3 10 43 PM" src="https://user-images.githubusercontent.com/16348315/134727957-242dec2d-6a81-4915-a148-dbfe00a37ea6.png">

**Comment by thomasjbradley** [comment]
> TABLE: I replaced thead with colgroup

You need both, like this:

```html
<table>
  <colgroup>
    <col>
  </colgroup>
  <thead>
    <tr>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
</table>
```

> Re: fonts, yes, I want to be able to use different font sizes at different screen sizes so increased

Unfortunately not a glitch, but a requirement of this assignment. There’s nothing wrong with using different font-sizes in media queries, this assignment is just forcing people to do it a specific way.

> Re: social icons, if these are based on the font size, does that mean that taking care of the previous issue would automatically resolve this issue? If these are not related and I'm supposed to use the classes on the Typografier cheat sheet, how can I apply them to tags for different screen sizes? If through media queries, how can I select the HTML tag, via some pseudo selector? Hope I'm not confusing you.

I don’t fully understand. But using the font-size icons dimensions will allow them to scale up & down on different screen sizes, but only proportional to the font size increases & decreases.

**Comment by C-G-G** [comment]
Thanks @thomasjbradley , almost there! All font-sizes have been removed from main.css so Markbot is happy and hopefully this will also help me explain my problem (the point that confuses me) better with an example: 

I want to be able to change (increase) the font-size for `.nav a` and `.sign + p` (index.html) at larger screens (logo too which is also text but let's pass that for now as this is probably not a professional practice anyways). Both these elements have a class of `pico` at base screen size. How can I increase the font-size without touching main.css?

**Comment by thomasjbradley** [comment]
Unfortunately, at this point, and with these Markbot requirements you cannot. In "the real world" there would be no problem doing it with media queries, this assignment is just very structured & strict. Intentional design limitations kinda thing.

**Comment by C-G-G** [comment]
Sounds good. Regardless, these are great assignments to practise what you learn and develop portfolio pieces. I'll submit as expected but may return to it later and complete as I wish to include in my portfolio. Thank you again, @thomasjbradley, for this platform, your support and patience!
